---
apiVersion: v1
kind: Service
metadata:
  name: snyk-juice-shop
  labels:
    app: snyk-juice-shop
spec:
  ports:
    - port: 8080
      targetPort: 3000
      protocol: TCP
  selector:
    app: snyk-juice-shop
    